package com.hanrolink.chat.enums;

public enum ProductSnapshotField {
  PRODUCT_CATEGORY,
  MAIN_INGREDIENT_ORIGIN_PREFECTURE,
  NAME,
  CONTENT_QUANTITY,
  EXPIRATION_TYPE,
  SHELF_LIFE_DAYS,
  STORAGE_TYPE,
  DESIRED_RETAIL_PRICE,
  ALLERGY_INFORMATION,
  CERTIFICATION_INFORMATION,
  CASE_SIZE,
  UNITS_PER_CASE,
  MINIMUM_ORDER_QUANTITY,
  SHIPPING_LEAD_TIME_DAYS,
  SALES_AREA_RESTRICTION,
  MONTHLY_SUPPLY_CAPACITIES,
  PRODUCT_STORIES
}
