spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.csrf: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
