spring:
  application:
    name: hanrolink-backend

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
