spring:
  application:
    name: hanrolink-backend

  profiles:
    group:
      prod:
        - cognito
        - s3
        - cloudfront

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
