/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetail"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-requests/{procurementRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetail_1"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/negotiation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/image-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_1"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-requests/{procurementRequestId}/negotiation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/supplier/product-negotiation-requests/{productNegotiationRequestId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/buyer/procurement-negotiation-requests/{procurementNegotiationRequestId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accept_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{channelId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create_6"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{channelId}/file-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_7"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{channelId}/file-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_8"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateVisibility"];
        trace?: never;
    };
    "/api/v1/admin/business-registrations/{businessId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["approve"];
        trace?: never;
    };
    "/api/v1/public/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/search-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/form-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-requests/search-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-requests/form-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-negotiation-requests/selectable-products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/supplier/product-negotiation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/supplier/procurement-negotiation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/procurement-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/buyer/product-negotiation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/buyer/procurement-negotiation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_9"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{channelId}/negotiation-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buyer/{businessId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/business-registrations/{businessId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetail_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/business-registrations/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MonthlySupplyCapacityRequest: {
            targetMonth: string;
            /** Format: int32 */
            availableQuantity: number;
        };
        ProductStoryUpdateRequest: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            position: number;
            /** Format: int32 */
            productStorySectionTemplateId: number;
            body: string;
            /** Format: uuid */
            pendingFileUploadId?: string;
        };
        SupplierProductUpdateRequest: {
            name: string;
            /** Format: int32 */
            productCategoryId: number;
            /** Format: int32 */
            mainIngredientOriginPrefectureId: number;
            /** Format: uuid */
            mainImagePendingFileUploadId?: string;
            contentQuantity: string;
            /** @enum {string} */
            expirationType: "BEST_BEFORE" | "USE_BY" | "NOT_APPLICABLE";
            /** Format: int32 */
            shelfLifeDays?: number;
            /** @enum {string} */
            storageType: "AMBIENT" | "REFRIGERATED" | "FROZEN";
            /** Format: int32 */
            desiredRetailPrice: number;
            allergyInformation?: string;
            certificationInformation?: string;
            caseSize?: string;
            /** Format: int32 */
            unitsPerCase?: number;
            /** Format: int32 */
            minimumOrderQuantity?: number;
            /** Format: int32 */
            shippingLeadTimeDays?: number;
            salesAreaRestriction?: string;
            monthlySupplyCapacities: components["schemas"]["MonthlySupplyCapacityRequest"][];
            productStories: components["schemas"]["ProductStoryUpdateRequest"][];
        };
        BuyerProcurementRequestUpdateRequest: {
            title: string;
            description: string;
            /** Format: int32 */
            productCategoryId: number;
            requiredTradeTerms?: string;
            /** Format: int32 */
            desiredUnitPrice?: number;
            /** Format: int32 */
            deliveryShelfLifeDays?: number;
            storageTypes: ("AMBIENT" | "REFRIGERATED" | "FROZEN")[];
            monthlyProcurementQuantities: components["schemas"]["MonthlyProcurementQuantityRequest"][];
        };
        MonthlyProcurementQuantityRequest: {
            targetMonth: string;
            /** Format: int32 */
            desiredQuantity: number;
        };
        ProductStoryCreateRequest: {
            /** Format: int32 */
            position: number;
            /** Format: int32 */
            productStorySectionTemplateId: number;
            body: string;
            /** Format: uuid */
            pendingFileUploadId: string;
        };
        SupplierProductCreateRequest: {
            name: string;
            /** Format: int32 */
            productCategoryId: number;
            /** Format: int32 */
            mainIngredientOriginPrefectureId: number;
            /** Format: uuid */
            mainImagePendingFileUploadId: string;
            contentQuantity: string;
            /** @enum {string} */
            expirationType: "BEST_BEFORE" | "USE_BY" | "NOT_APPLICABLE";
            /** Format: int32 */
            shelfLifeDays?: number;
            /** @enum {string} */
            storageType: "AMBIENT" | "REFRIGERATED" | "FROZEN";
            /** Format: int32 */
            desiredRetailPrice: number;
            allergyInformation?: string;
            certificationInformation?: string;
            caseSize?: string;
            /** Format: int32 */
            unitsPerCase?: number;
            /** Format: int32 */
            minimumOrderQuantity?: number;
            /** Format: int32 */
            shippingLeadTimeDays?: number;
            salesAreaRestriction?: string;
            monthlySupplyCapacities: components["schemas"]["MonthlySupplyCapacityRequest"][];
            productStories: components["schemas"]["ProductStoryCreateRequest"][];
        };
        SupplierProductCreateResponse: {
            /** Format: uuid */
            id: string;
        };
        SupplierProductImageUploadCreateRequest: {
            /** @enum {string} */
            usage: "MAIN_IMAGE" | "STORY_IMAGE";
            /** Format: int64 */
            fileSizeBytes: number;
        };
        SupplierProductImageUploadCreateResponse: {
            uploadUrl: string;
            /** Format: uuid */
            pendingFileUploadId: string;
        };
        BuyerProcurementRequestCreateRequest: {
            title: string;
            description: string;
            /** Format: int32 */
            productCategoryId: number;
            requiredTradeTerms?: string;
            /** Format: int32 */
            desiredUnitPrice?: number;
            /** Format: int32 */
            deliveryShelfLifeDays?: number;
            storageTypes: ("AMBIENT" | "REFRIGERATED" | "FROZEN")[];
            monthlyProcurementQuantities: components["schemas"]["MonthlyProcurementQuantityRequest"][];
        };
        BuyerProcurementRequestCreateResponse: {
            /** Format: uuid */
            id: string;
        };
        SupplierSentNegotiationRequestCreateRequest: {
            /** Format: uuid */
            productId: string;
        };
        OnboardingBusinessRequest: {
            /** @enum {string} */
            role: "SUPPLIER" | "BUYER";
            name: string;
            nameKana: string;
            websiteUrl?: string;
            addressPostalCode: string;
            addressPrefecture: string;
            addressMunicipalityStreet: string;
            addressBuilding?: string;
            phoneNumber: string;
        };
        OnboardingBusinessUserAccountRequest: {
            lastName: string;
            firstName: string;
            lastNameKana: string;
            firstNameKana: string;
            phoneNumber: string;
        };
        OnboardingCreateRequest: {
            business: components["schemas"]["OnboardingBusinessRequest"];
            businessUserAccount: components["schemas"]["OnboardingBusinessUserAccountRequest"];
        };
        OnboardingCreateResponse: {
            /** @enum {string} */
            businessUserAccountRegistrationStatus: "NOT_SUBMITTED" | "PENDING" | "APPROVED";
        };
        NegotiationRequestAcceptResponse: {
            channel: components["schemas"]["NegotiationRequestChannelResponse"];
        };
        NegotiationRequestChannelResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            counterpartyBusinessName: string;
            /** Format: date-time */
            lastActivityAt: string;
        };
        MyChatMessageCreateRequest: {
            body?: string;
            pendingFileUploadIds?: string[];
            contentPresent?: boolean;
        };
        MyChatFileUploadCreateRequest: {
            /** @enum {string} */
            mimeType: "image/webp" | "application/pdf";
            displayFilename: string;
            /** Format: int64 */
            fileSizeBytes: number;
            fileSizeWithinLimit?: boolean;
        };
        MyChatFileUploadCreateResponse: {
            uploadUrl: string;
            /** Format: uuid */
            pendingFileUploadId: string;
        };
        SupplierProductUpdateVisibilityRequest: {
            hidden: boolean;
        };
        PublicProductListResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            supplierBusinessName: string;
            mainImageUrl: string;
        };
        MonthlySupplyCapacityResponse: {
            targetMonth: string;
            /** Format: int32 */
            availableQuantity: number;
        };
        PaginationResponse: {
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            totalCount: number;
            /** Format: int32 */
            totalPages: number;
        };
        ProductSearchResponse: {
            products: components["schemas"]["ProductSearchResultResponse"][];
            pagination: components["schemas"]["PaginationResponse"];
        };
        ProductSearchResultResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            businessName: string;
            productCategoryName: string;
            mainIngredientOriginPrefectureName: string;
            storageTypeLabel: string;
            monthlySupplyCapacities: components["schemas"]["MonthlySupplyCapacityResponse"][];
            mainImageUrl: string;
        };
        ProductCategoryResponse: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        ProductDetailResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            hidden: boolean;
            productCategory: components["schemas"]["ProductCategoryResponse"];
            mainIngredientOriginPrefecture: components["schemas"]["ProductMainIngredientOriginPrefectureResponse"];
            contentQuantity: string;
            productExpirationType: components["schemas"]["ProductExpirationTypeResponse"];
            /** Format: int32 */
            shelfLifeDays?: number;
            storageType: components["schemas"]["StorageTypeResponse"];
            /** Format: int32 */
            desiredRetailPrice: number;
            allergyInformation?: string;
            certificationInformation?: string;
            caseSize?: string;
            /** Format: int32 */
            unitsPerCase?: number;
            /** Format: int32 */
            minimumOrderQuantity?: number;
            /** Format: int32 */
            shippingLeadTimeDays?: number;
            salesAreaRestriction?: string;
            mainImageUrl: string;
            monthlySupplyCapacities: components["schemas"]["MonthlySupplyCapacityResponse"][];
            productStories: components["schemas"]["ProductStoryResponse"][];
            supplier: components["schemas"]["ProductSupplierResponse"];
            permissions: components["schemas"]["ProductPermissionsResponse"];
            hasMyActiveNegotiationRequest: boolean;
        };
        ProductExpirationTypeResponse: {
            /** @enum {string} */
            value: "BEST_BEFORE" | "USE_BY" | "NOT_APPLICABLE";
            label: string;
        };
        ProductMainIngredientOriginPrefectureResponse: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        ProductPermissionsResponse: {
            canManage: boolean;
            canCreateNegotiationRequest: boolean;
        };
        ProductStoryResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            productStorySectionTemplateId: number;
            /** Format: int32 */
            position: number;
            sectionTitle: string;
            body: string;
            imageUrl: string;
        };
        ProductSupplierResponse: {
            businessName: string;
            businessAddressPrefecture: string;
            businessAddressMunicipalityStreet: string;
            businessAddressBuilding?: string;
            businessWebsiteUrl?: string;
        };
        StorageTypeResponse: {
            /** @enum {string} */
            value: "AMBIENT" | "REFRIGERATED" | "FROZEN";
            label: string;
        };
        ProductCategoryGroupOptionResponse: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        ProductCategoryOptionResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            productCategoryGroupId: number;
            name: string;
        };
        ProductSearchOptionsResponse: {
            productCategoryGroups: components["schemas"]["ProductCategoryGroupOptionResponse"][];
            productCategories: components["schemas"]["ProductCategoryOptionResponse"][];
            mainIngredientOriginRegions: components["schemas"]["RegionOptionResponse"][];
            storageTypes: components["schemas"]["StorageTypeOptionResponse"][];
        };
        RegionOptionResponse: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        StorageTypeOptionResponse: {
            /** @enum {string} */
            value: "AMBIENT" | "REFRIGERATED" | "FROZEN";
            label: string;
        };
        PrefectureOptionResponse: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        ProductExpirationTypeOptionResponse: {
            /** @enum {string} */
            value: "BEST_BEFORE" | "USE_BY" | "NOT_APPLICABLE";
            label: string;
        };
        ProductStorySectionTemplateOptionResponse: {
            /** Format: int32 */
            id: number;
            title: string;
            imageHint: string;
            bodyHelpText: string;
            bodyExample: string;
        };
        SupplierProductFormOptionsResponse: {
            productCategoryGroups: components["schemas"]["ProductCategoryGroupOptionResponse"][];
            productCategories: components["schemas"]["ProductCategoryOptionResponse"][];
            mainIngredientOriginPrefectures: components["schemas"]["PrefectureOptionResponse"][];
            productExpirationTypes: components["schemas"]["ProductExpirationTypeOptionResponse"][];
            storageTypes: components["schemas"]["StorageTypeOptionResponse"][];
            productStorySectionTemplates: components["schemas"]["ProductStorySectionTemplateOptionResponse"][];
        };
        MonthlyProcurementQuantityResponse: {
            targetMonth: string;
            /** Format: int32 */
            desiredQuantity: number;
        };
        ProcurementRequestBuyerResponse: {
            /** Format: uuid */
            businessId: string;
            businessName: string;
        };
        ProcurementRequestSearchResponse: {
            procurementRequests: components["schemas"]["ProcurementRequestSearchResultResponse"][];
            pagination: components["schemas"]["PaginationResponse"];
        };
        ProcurementRequestSearchResultResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            productCategoryName: string;
            storageTypeLabels: string[];
            monthlyProcurementQuantities: components["schemas"]["MonthlyProcurementQuantityResponse"][];
            buyer: components["schemas"]["ProcurementRequestBuyerResponse"];
        };
        ProcurementRequestDetailResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            buyer: components["schemas"]["ProcurementRequestBuyerResponse"];
            productCategory: components["schemas"]["ProductCategoryResponse"];
            requiredTradeTerms?: string;
            /** Format: int32 */
            desiredUnitPrice?: number;
            /** Format: int32 */
            deliveryShelfLifeDays?: number;
            storageTypes: components["schemas"]["StorageTypeResponse"][];
            monthlyProcurementQuantities: components["schemas"]["MonthlyProcurementQuantityResponse"][];
            permissions: components["schemas"]["ProcurementRequestPermissionsResponse"];
            hasMyActiveNegotiationRequest: boolean;
        };
        ProcurementRequestPermissionsResponse: {
            canManage: boolean;
            canCreateNegotiationRequest: boolean;
        };
        ProcurementRequestSearchOptionsResponse: {
            productCategoryGroups: components["schemas"]["ProductCategoryGroupOptionResponse"][];
            productCategories: components["schemas"]["ProductCategoryOptionResponse"][];
            storageTypes: components["schemas"]["StorageTypeOptionResponse"][];
        };
        BuyerProcurementRequestFormOptionsResponse: {
            productCategoryGroups: components["schemas"]["ProductCategoryGroupOptionResponse"][];
            productCategories: components["schemas"]["ProductCategoryOptionResponse"][];
            storageTypes: components["schemas"]["StorageTypeOptionResponse"][];
        };
        SupplierNegotiationRequestSelectableProductResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            mainImageUrl: string;
        };
        OnboardingGetResponse: {
            email: string;
        };
        CurrentAccountGetResponse: {
            /** @enum {string|null} */
            role: "ADMIN" | "SUPPLIER" | "BUYER" | null;
            /** @enum {string|null} */
            businessUserAccountRegistrationStatus: "NOT_SUBMITTED" | "PENDING" | "APPROVED" | null;
        };
        NegotiationRequestProductResponse: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        NegotiationRequestSenderBusinessResponse: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        SupplierReceivedNegotiationRequestListResponse: {
            /** Format: uuid */
            id: string;
            product: components["schemas"]["NegotiationRequestProductResponse"];
            senderBusiness: components["schemas"]["NegotiationRequestSenderBusinessResponse"];
            /** Format: date-time */
            expiresAt: string;
        };
        NegotiationRequestProcurementRequestResponse: {
            /** Format: uuid */
            id: string;
            title: string;
        };
        SupplierSentNegotiationRequestListResponse: {
            /** Format: uuid */
            id: string;
            procurementRequest: components["schemas"]["NegotiationRequestProcurementRequestResponse"];
            product: components["schemas"]["NegotiationRequestProductResponse"];
            /** Format: date-time */
            expiresAt: string;
        };
        SupplierProductListResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            mainImageUrl: string;
            hidden: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        BuyerProcurementRequestListResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MyChatListResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            lastActivityAt: string;
        };
        BuyerSentNegotiationRequestListResponse: {
            /** Format: uuid */
            id: string;
            product: components["schemas"]["NegotiationRequestProductResponse"];
            /** Format: date-time */
            expiresAt: string;
        };
        BuyerReceivedNegotiationRequestListResponse: {
            /** Format: uuid */
            id: string;
            procurementRequest: components["schemas"]["NegotiationRequestProcurementRequestResponse"];
            product: components["schemas"]["NegotiationRequestProductResponse"];
            senderBusinessName: string;
            /** Format: date-time */
            expiresAt: string;
        };
        CurrentBusinessGetResponse: {
            businessName: string;
        };
        MyChatOverviewResponse: {
            channelName: string;
            counterpartyBusinessName: string;
        };
        MonthlyProcurementQuantitySnapshotResponse: {
            targetMonth: string;
            /** Format: int32 */
            desiredQuantity: number;
        };
        MonthlySupplyCapacitySnapshotResponse: {
            targetMonth: string;
            /** Format: int32 */
            availableQuantity: number;
        };
        MyChatNegotiationSnapshotResponse: {
            /** @enum {string} */
            negotiationTargetType: "PRODUCT" | "PROCUREMENT_REQUEST";
            productChangedFields: ("PRODUCT_CATEGORY" | "MAIN_INGREDIENT_ORIGIN_PREFECTURE" | "NAME" | "CONTENT_QUANTITY" | "EXPIRATION_TYPE" | "SHELF_LIFE_DAYS" | "STORAGE_TYPE" | "DESIRED_RETAIL_PRICE" | "ALLERGY_INFORMATION" | "CERTIFICATION_INFORMATION" | "CASE_SIZE" | "UNITS_PER_CASE" | "MINIMUM_ORDER_QUANTITY" | "SHIPPING_LEAD_TIME_DAYS" | "SALES_AREA_RESTRICTION" | "MONTHLY_SUPPLY_CAPACITIES" | "PRODUCT_STORIES")[];
            requestedProductSnapshot: components["schemas"]["ProductSnapshotResponse"];
            acceptedProductSnapshot: components["schemas"]["ProductSnapshotResponse"];
            procurementRequestChangedFields?: ("PRODUCT_CATEGORY" | "TITLE" | "DESCRIPTION" | "REQUIRED_TRADE_TERMS" | "DESIRED_UNIT_PRICE" | "DELIVERY_SHELF_LIFE_DAYS" | "STORAGE_TYPES" | "MONTHLY_PROCUREMENT_QUANTITIES")[];
            requestedProcurementRequestSnapshot?: components["schemas"]["ProcurementRequestSnapshotResponse"];
            acceptedProcurementRequestSnapshot?: components["schemas"]["ProcurementRequestSnapshotResponse"];
        };
        ProcurementRequestSnapshotResponse: {
            productCategoryName: string;
            title: string;
            description: string;
            requiredTradeTerms?: string;
            /** Format: int32 */
            desiredUnitPrice?: number;
            /** Format: int32 */
            deliveryShelfLifeDays?: number;
            storageTypeNames: string[];
            monthlyProcurementQuantities: components["schemas"]["MonthlyProcurementQuantitySnapshotResponse"][];
        };
        ProductSnapshotResponse: {
            productCategoryName: string;
            mainIngredientOriginPrefectureName: string;
            name: string;
            contentQuantity: string;
            expirationTypeName: string;
            /** Format: int32 */
            shelfLifeDays?: number;
            storageTypeName: string;
            /** Format: int32 */
            desiredRetailPrice: number;
            allergyInformation?: string;
            certificationInformation?: string;
            caseSize?: string;
            /** Format: int32 */
            unitsPerCase?: number;
            /** Format: int32 */
            minimumOrderQuantity?: number;
            /** Format: int32 */
            shippingLeadTimeDays?: number;
            salesAreaRestriction?: string;
            monthlySupplyCapacities: components["schemas"]["MonthlySupplyCapacitySnapshotResponse"][];
            productStories: components["schemas"]["ProductStorySnapshotResponse"][];
        };
        ProductStorySnapshotResponse: {
            sectionTitle: string;
            body: string;
        };
        ChatMessageFileResponse: {
            displayFilename: string;
            url: string;
            /** Format: int64 */
            fileSizeBytes: number;
        };
        MyChatMessageListResponse: {
            /** Format: int64 */
            id: number;
            senderBusinessName: string;
            isMine: boolean;
            body?: string;
            /** Format: date-time */
            createdAt: string;
            messageFiles?: components["schemas"]["ChatMessageFileResponse"][];
        };
        BuyerProfileGetResponse: {
            businessName: string;
            businessAddressPrefecture: string;
            businessAddressMunicipalityStreet: string;
            businessAddressBuilding?: string;
            websiteUrl?: string;
        };
        AdminBusinessApprovalDetailResponse: {
            business: components["schemas"]["BusinessApprovalBusinessResponse"];
            businessUserAccount: components["schemas"]["BusinessApprovalAccountResponse"];
        };
        BusinessApprovalAccountResponse: {
            lastName: string;
            firstName: string;
            lastNameKana: string;
            firstNameKana: string;
            phoneNumber: string;
            email: string;
        };
        BusinessApprovalBusinessResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "SUPPLIER" | "BUYER";
            /** @enum {string} */
            reviewStatus: "PENDING" | "APPROVED";
            name: string;
            nameKana: string;
            websiteUrl?: string;
            addressPostalCode: string;
            addressPrefecture: string;
            addressMunicipalityStreet: string;
            addressBuilding?: string;
            phoneNumber: string;
            /** Format: date-time */
            createdAt: string;
        };
        AdminBusinessApprovalListResponse: {
            /** Format: uuid */
            businessId: string;
            businessName: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductDetailResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierProductUpdateRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDetail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                procurementRequestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcurementRequestDetailResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                procurementRequestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyerProcurementRequestUpdateRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                procurementRequestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search: {
        parameters: {
            query?: {
                availableSupplyMonths?: string[];
                mainIngredientOriginRegionIds?: number[];
                productCategoryIds?: number[];
                storageTypes?: ("AMBIENT" | "REFRIGERATED" | "FROZEN")[];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductSearchResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierProductCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierProductCreateResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierProductImageUploadCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierProductImageUploadCreateResponse"];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query?: {
                desiredProcurementMonths?: string[];
                productCategoryIds?: number[];
                storageTypes?: ("AMBIENT" | "REFRIGERATED" | "FROZEN")[];
                keyword?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcurementRequestSearchResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyerProcurementRequestCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BuyerProcurementRequestCreateResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                procurementRequestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierSentNegotiationRequestCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnboardingGetResponse"];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnboardingCreateResponse"];
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productNegotiationRequestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NegotiationRequestAcceptResponse"];
                };
            };
        };
    };
    accept_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                procurementNegotiationRequestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NegotiationRequestAcceptResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                limit?: number;
                beforeMessageId?: number;
                afterMessageId?: number;
            };
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyChatMessageListResponse"][];
                };
            };
        };
    };
    create_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MyChatMessageCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MyChatFileUploadCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyChatFileUploadCreateResponse"];
                };
            };
        };
    };
    create_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateVisibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierProductUpdateVisibilityRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                businessId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicProductListResponse"][];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductSearchOptionsResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierProductFormOptionsResponse"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcurementRequestSearchOptionsResponse"];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BuyerProcurementRequestFormOptionsResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierNegotiationRequestSelectableProductResponse"][];
                };
            };
        };
    };
    get_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentAccountGetResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierReceivedNegotiationRequestListResponse"][];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierSentNegotiationRequestListResponse"][];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierProductListResponse"][];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BuyerProcurementRequestListResponse"][];
                };
            };
        };
    };
    list_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyChatListResponse"][];
                };
            };
        };
    };
    list_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BuyerSentNegotiationRequestListResponse"][];
                };
            };
        };
    };
    list_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BuyerReceivedNegotiationRequestListResponse"][];
                };
            };
        };
    };
    get_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentBusinessGetResponse"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyChatOverviewResponse"];
                };
            };
        };
    };
    get_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyChatNegotiationSnapshotResponse"];
                };
            };
        };
    };
    get_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                businessId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BuyerProfileGetResponse"];
                };
            };
        };
    };
    getDetail_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                businessId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminBusinessApprovalDetailResponse"];
                };
            };
        };
    };
    listPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminBusinessApprovalListResponse"][];
                };
            };
        };
    };
}
